[package]
name = "vortex-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true , features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
vortex-types = { workspace = true }